### PR TITLE
Scale minSize/maxSize properly.

### LINKED ISSUE #40: boxWidth/Height fails to scale maxSize, minSize round-off error
1. If boxWidth or boxHeight is set and image is downscaled, maxSize fails to scale down.
   minSize limits the selection properly (except for the round-off error described below).
   maxSize limits the selection to actual pixels of maxSize, not the scaled-down value of MaxSize.
2. With big images, minSize restriction reports with an error between 1 and 4 px. Example:
3. Image is 1800px wide
4. boxWidth: 500
5. minSize: [100, 100]
6. minimal crop reports w: 98, h: 98; It should have stopped just one pixel earlier (which is 102x102), or return 100x100.

Its a small difference, but I'd rather be on the upper side of a round-off than the lower. :) 
"Uglish" rudimentary hack would be to return 100x100 even if actual value is 98 or 101 - at these scale rates, it holds 3,25 actual image pixels within one display pixel, so rounding it to the actual minSize dimensions on an already approximate minimal crop would still hold a true representation of what the user actually sees.

### PR DESCRIPTION
**Pull request by rmcdaniel**
This fixes #40 issue with minSize/maxSize scaling when using boxWidth/boxHeight or trueSize.

### CODE REVIEW

**Comment by Mickey-** [comment]
good job

**Comment by rmcdaniel** [comment]
I recommend using https://github.com/fengyuanchen/cropper which is what I've switched to.

**Comment by metric152** [comment]
Can someone please pull in this fix? It solved a huge issue for me.

**Comment by Mickey-** [comment]
Now we can hack it by extra logic:

```javascript
        $(ele).Jcrop(cropOptions, function(){
          var jcrop = this
          if (cropOptions.maxSize) {
            jcrop.setOptions({
              maxSize: [cropOptions.maxSize[0] / jcrop.getScaleFactor()[0], cropOptions.maxSize[1] / jcrop.getScaleFactor()[1]]
            })
          }
        })

```

**Comment by rabe85** [comment]
Is there also a fix for the v2.0.0-RC1 version?

**Comment by metric152** [comment]
This pull actually breaks some stuff. It changes the rounding on the selection. If I manually enter a selection dimension for a scaled image it comes back wrong.

**Pull request closed without merging**
